/**
 * Parse given template string with each context.
 * @param {string} str The template string
 * @param {any} ctx The context key/value
 * @returns {string} The template value
 */
export declare function parseTemplate(str: string, ctx: any): string;
export declare const editorTemplate = "\n  <div class=\"ids-editor\" part=\"editor\"{disabled}{readonly}>\n    <slot class=\"{hiddenClass}\"></slot>\n    <ids-text id=\"editor-label\" label class=\"{labelClass}{hiddenLabelCss}{requiredLabelCss}\" part=\"editor-label\"{disabled}{readonly}>{labelText}</ids-text>\n    <div class=\"main-container\" part=\"main-container\">\n      <div class=\"toolbar-container\" part=\"toolbar-container\">\n        <slot name=\"toolbar\"></slot>\n      </div>\n      <div class=\"editor-content\">\n        <div id=\"editor-container\" class=\"editor-container\" part=\"editor-container\"{contenteditable} aria-multiline=\"true\" role=\"textbox\" aria-labelledby=\"editor-label\"{placeholder}></div>\n        <div class=\"source-container {hiddenClass}\" part=\"source-container\">\n          <div class=\"source-wrapper\">\n            <ul class=\"line-numbers\"></ul>\n            <label class=\"audible\" for=\"source-textarea\">\n              {sourceTextareaLabel}\n            </label>\n            <textarea id=\"source-textarea\" class=\"source-textarea\"{placeholder}></textarea>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>";
export declare const btnEditorModeTemplate = "\n  <ids-button editor-action=\"editormode\" square=\"true\" tooltip=\"View Visual\" color-variant=\"alternate-formatter\">\n    <span class=\"audible\">View Visual</span>\n    <ids-icon icon=\"visual\" width=\"50\" viewbox=\"0 0 73 18\"></ids-icon>\n  </ids-button>";
export declare const btnSourceModeTemplate = "\n  <ids-button editor-action=\"sourcemode\" square=\"true\" tooltip=\"View Source\" color-variant=\"alternate-formatter\">\n    <span class=\"audible\">View Source</span>\n    <ids-icon icon=\"html\" width=\"38\" viewbox=\"0 0 54 18\"></ids-icon>\n  </ids-button>";
export declare const toolbarTemplate: string;
export declare const errorMessageTemplate = "\n  <ids-message id=\"errormessage-modal\" status=\"error\">\n    <ids-text slot=\"title\" font-size=\"24\" type=\"h2\" id=\"errormessage-modal-title\">No Selection!</ids-text>\n    <ids-text class=\"demo-contents\" align=\"left\">Please make some selection to complete this task.</ids-text>\n    <ids-modal-button slot=\"buttons\" appearance=\"primary\" id=\"errormessage-modal-ok\">OK</ids-modal-button>\n  </ids-message>";
export declare const hyperlinkModalTemplate = "\n  <ids-modal id=\"{key}-modal\">\n    <ids-text slot=\"title\" font-size=\"24\" type=\"h2\" id=\"{key}-modal-title\">Insert Anchor</ids-text>\n    <ids-layout-grid class=\"data-grid-container\" auto=\"true\" gap=\"md\" no-margins=\"true\" min-col-width=\"300px\">\n      <ids-layout-grid-cell>\n        <ids-input id=\"{key}-modal-input-url\" label=\"Url\" value=\"{url}\" validate=\"required\"></ids-input>\n        {clickableElemHtml}\n        <ids-input id=\"{key}-modal-input-classes\" label=\"Css Class\" value=\"{classes}\"></ids-input>\n        {targetDropdownHtml}\n        <div id=\"{key}-modal-checkbox-remove-container\" class=\"{hiddenClass}\">\n          <ids-checkbox id=\"{key}-modal-checkbox-remove\" label=\"Remove hyperlink\"></ids-checkbox>\n        </div>\n      </ids-layout-grid-cell>\n    </ids-layout-grid>\n    <ids-modal-button slot=\"buttons\" id=\"{key}-modal-cancel-btn\" appearance=\"secondary\">\n      <span>Cancel</span>\n    </ids-modal-button>\n    <ids-modal-button slot=\"buttons\" id=\"{key}-modal-apply-btn\" appearance=\"primary\">\n      <span>Apply</span>\n    </ids-modal-button>\n  </ids-modal>";
export declare const insertimageModalTemplate = "\n  <ids-modal id=\"{key}-modal\">\n    <ids-text slot=\"title\" font-size=\"24\" type=\"h2\" id=\"{key}-modal-title\">Insert Image</ids-text>\n    <ids-layout-grid class=\"data-grid-container\" auto=\"true\" gap=\"md\" no-margins=\"true\" min-col-width=\"300px\">\n      <ids-layout-grid-cell>\n        <ids-input id=\"{key}-modal-input-src\" label=\"Url\" value=\"{url}\" validate=\"required\"></ids-input>\n        <ids-input id=\"{key}-modal-input-alt\" label=\"Alt text\" value=\"{alt}\"></ids-input>\n      </ids-layout-grid-cell>\n    </ids-layout-grid>\n\n    <ids-modal-button slot=\"buttons\" id=\"{key}-modal-cancel-btn\" appearance=\"secondary\">\n      <span>Cancel</span>\n    </ids-modal-button>\n    <ids-modal-button slot=\"buttons\" id=\"{key}-modal-apply-btn\" appearance=\"primary\">\n      <span>Apply</span>\n    </ids-modal-button>\n  </ids-modal>";
