export declare const WORKBOOK_XML = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:mx=\"http://schemas.microsoft.com/office/mac/excel/2008/main\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\" xmlns:mv=\"urn:schemas-microsoft-com:mac:vml\" xmlns:x14=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/main\" xmlns:x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\" xmlns:xm=\"http://schemas.microsoft.com/office/excel/2006/main\"><workbookPr/><sheets><sheet state=\"visible\" name=\"Sheet1\" sheetId=\"1\" r:id=\"rId3\"/></sheets><definedNames/><calcPr/></workbook>";
export declare const WORKBOOK_XML_REL = "<?xml version=\"1.0\" ?>\n<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\n<Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>\n<Relationship Id=\"rId3\" Target=\"worksheets/sheet1.xml\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\"/>\n</Relationships>";
export declare const RELS = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>";
export declare const CONTENT_TYPES = "<?xml version=\"1.0\" ?>\n<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">\n<Default ContentType=\"application/xml\" Extension=\"xml\"/>\n<Default ContentType=\"application/vnd.openxmlformats-package.relationships+xml\" Extension=\"rels\"/>\n<Override ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\" PartName=\"/xl/worksheets/sheet1.xml\"/>\n<Override ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\" PartName=\"/xl/workbook.xml\"/>\n<Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>\n</Types>";
export declare const WORKSHEET_TEMPLATE = "<?xml version=\"1.0\" ?>\n<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\" xmlns:mv=\"urn:schemas-microsoft-com:mac:vml\" xmlns:mx=\"http://schemas.microsoft.com/office/mac/excel/2008/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:x14=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/main\" xmlns:x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\" xmlns:xm=\"http://schemas.microsoft.com/office/excel/2006/main\">\n<cols>{colPlaceholder}</cols>\n<sheetData>{sheetDataPlaceholder}</sheetData>\n</worksheet>";
export declare const STYLES_XML = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<styleSheet mc:Ignorable=\"x14ac x16r2 xr\"\n  xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"\n  xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\"\n  xmlns:x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\"\n  xmlns:x16r2=\"http://schemas.microsoft.com/office/spreadsheetml/2015/02/main\"\n  xmlns:xr=\"http://schemas.microsoft.com/office/spreadsheetml/2014/revision\">\n  <numFmts count=\"0\"></numFmts>\n  <fonts count=\"3\">\n    <font>\n      <sz val=\"11\" />\n      <color theme=\"1\" rgb=\"FF000000\" />\n      <name val=\"Calibri\" />\n      <family val=\"2\" />\n      <scheme val=\"minor\" />\n    </font>\n    <font>\n      <sz val=\"11\" />\n      <color rgb=\"FFff0000\" />\n      <name val=\"Calibri Light\" />\n    </font>\n    <font>\n      <b />\n      <sz val=\"11\" />\n      <color rgb=\"FF000000\" />\n      <name val=\"Calibri Light\" />\n    </font>\n  </fonts>\n  <fills count=\"4\">\n    <fill>\n      <patternFill patternType=\"none\" />\n    </fill>\n  </fills>\n  <borders count=\"1\">\n    <border>\n      <left />\n      <right />\n      <top />\n      <bottom />\n      <diagonal />\n    </border>\n    <border>\n      <begin/>\n      <end style=\"thin\">\n        <color indexed=\"64\"/>\n      </end>\n      <top/>\n      <bottom style=\"thin\">\n        <color indexed=\"64\"/>\n      </bottom>\n      <diagonal/>\n    </border>\n  </borders>\n  <cellStyleXfs count=\"1\">\n    <xf borderId=\"0\" fillId=\"0\" fontId=\"0\" numFmtId=\"0\" />\n  </cellStyleXfs>\n  <cellXfs count=\"4\">\n    <xf borderId=\"0\" fillId=\"0\" fontId=\"0\" numFmtId=\"0\" xfId=\"0\" />\n    <xf applyFont=\"1\" borderId=\"1\" fillId=\"0\" fontId=\"2\" numFmtId=\"0\" xfId=\"0\" applyAlignment=\"1\">\n      <alignment horizontal=\"center\" />\n    </xf>\n    <xf borderId=\"0\" fillId=\"0\" fontId=\"0\" numFmtId=\"14\" xfId=\"0\" applyNumberFormat=\"1\" />\n    <xf borderId=\"0\" fillId=\"0\" fontId=\"0\" numFmtId=\"18\" xfId=\"0\" applyNumberFormat=\"1\" />\n  </cellXfs>\n  <tableStyles count=\"0\" defaultPivotStyle=\"PivotStyleLight16\" defaultTableStyle=\"TableStyleMedium2\" />\n</styleSheet>";
export interface ExcelColumn {
    id: string;
    field: string;
    type: string;
    name: string;
}
export interface XLSXColumn extends ExcelColumn {
    refLetter: string;
    width: number;
}
export interface ExcelConfig {
    filename: string;
    columns: Array<ExcelColumn>;
}
